#!/bin/bash
read -p "MFA Token: " TOKEN </dev/tty

RET=$(aws --output text sts get-session-token --serial-number arn:aws:iam::$AWS_ACCOUNT_NUMBER:mfa/$AWS_ACCOUNT_USERNAME --token $TOKEN)
AWS_ACCESS_KEY_ID=$(echo $RET | awk '{print $2}')
echo export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY=$(echo $RET | awk '{print $4}')
echo export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
AWS_SECURITY_TOKEN=$(echo $RET | awk '{print $5}')
echo export AWS_SECURITY_TOKEN="$AWS_SECURITY_TOKEN"
echo export AWS_SESSION_TOKEN="$AWS_SECURITY_TOKEN"
