#! /bin/bash
# This is a general-purpose function to ask Yes/No questions in Bash, either
# with or without a default answer. It keeps repeating the question until it
# gets a valid answer.

ask() {
  # http://djm.me/ask
  while true; do

    if [ "${2:-}" = "Y" ]; then
      prompt="Y/n"
      default=Y
    elif [ "${2:-}" = "N" ]; then
      prompt="y/N"
      default=N
    else
      prompt="y/n"
      default=
    fi

    # Ask the question - use /dev/tty in case stdin is redirected from somewhere else
    read -p "$1 [$prompt] " REPLY </dev/tty

    # Default?
    if [ -z "$REPLY" ]; then
      REPLY=$default
    fi

    # Check if the reply is valid
    case "$REPLY" in
      Y*|y*) return 0 ;;
      N*|n*) return 1 ;;
    esac

  done
}



if ask "Do you want to initialize aws_token?" N; then
  session_name=OP_SESSION_$ONEPASS_ACCOUNT
  export OP_SESSION=$(op signin $ONEPASS_ACCOUNT --output=raw)
  echo $session_name="$OP_SESSION"
  export $session_name="$OP_SESSION"
  export DOCUMENT=$(op get document $ONEPASS_DOCUMENT)
  export AWS_ACCESS_KEY_ID=$(echo $DOCUMENT | jq ".key" | tr -ds '"' '')
  echo export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
  export AWS_SECRET_ACCESS_KEY=$(echo $DOCUMENT | jq ".secret" | tr -ds '"' '')
  echo export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
  exec "~/.init/aws_mfa"
fi
