#! /bin/bash
# This is a general-purpose function to ask Yes/No questions in Bash, either
# with or without a default answer. It keeps repeating the question until it
# gets a valid answer.

ask() {
  # http://djm.me/ask
  while true; do

    if [ "${2:-}" = "Y" ]; then
      prompt="Y/n"
      default=Y
    elif [ "${2:-}" = "N" ]; then
      prompt="y/N"
      default=N
    else
      prompt="y/n"
      default=
    fi

    # Ask the question - use /dev/tty in case stdin is redirected from somewhere else
    read -p "$1 [$prompt] " REPLY </dev/tty

    # Default?
    if [ -z "$REPLY" ]; then
      REPLY=$default
    fi

    # Check if the reply is valid
    case "$REPLY" in
      Y*|y*) return 0 ;;
      N*|n*) return 1 ;;
    esac

  done
}



if ask "Do you want to initialize aws_token?" N; then
  lpass login $LPASS_USERNAME 2>&1 >/dev/null
  export AWS_ACCESS_KEY_ID=$(lpass show --notes AWS_ACCESS_KEY_ID)
  echo export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
  export AWS_SECRET_ACCESS_KEY=$(lpass show --notes AWS_SECRET_ACCESS_KEY)
  echo export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
  exec "~/.init/aws_mfa"
fi
